// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktqljjulaxgpwuiyjlik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cWxqanVsYXhncHd1aXlqbGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDM1NDgsImV4cCI6MjA2NjgxOTU0OH0.Sfxe30QuyPczDlclh2BxSCfvzodFLcD9DDQiVkL2uj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});